apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo-app-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demo-app
  template:
    metadata:
      labels:
        app: python-demo-app
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: python-demo-app-web
          # image: python-demo-app:init
          # args:
          #   - '--bind'
          #   - '0.0.0.0'
          #   - 'app:app'
          image: nginx

          ports:
            - name: gunicorn
              containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m